---
- hosts: jenkins
  become: yes

  tasks:
    - name: Update APT package index
      apt:
        update_cache: yes

    - name: Install dependencies for Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add ubuntu user to Docker group
      ansible.builtin.user:
        name: "ubuntu"
        groups: docker
        append: yes

    - name: Run Jenkins container
      community.docker.docker_container:
        name: jenkins
        image: jenkins/jenkins:lts
        state: started
        restart_policy: always
        ports:
          - "8080:8080"
        volumes:
          - jenkins_home:/var/jenkins_home
          - /var/run/docker.sock:/var/run/docker.sock 

    - name: Wait for Jenkins to start
      wait_for:
        port: 8080
        delay: 10
        timeout: 60

    - name: Update package list inside Jenkins container
      community.docker.docker_container_exec:
        container: jenkins
        command: apt-get update
        user: root      

    - name: Install curl inside Jenkins container
      community.docker.docker_container_exec:
        container: jenkins
        command: apt-get install -y curl
        user: root


    - name: Check if Docker is installed inside Jenkins container
      community.docker.docker_container_exec:
        container: jenkins
        command: /usr/bin/docker --version
      register: docker_installed
      ignore_errors: true

    - name: Install Docker inside Jenkins container if not installed
      community.docker.docker_container_exec:
        container: jenkins
        command: >
          /bin/bash -c "curl -fsSL https://get.docker.com/ -o dockerinstall && 
          chmod +x dockerinstall && 
          ./dockerinstall"
        user: root
      when: docker_installed is failed  # Only run if Docker is not installed

    - name: Change permissions on Docker socket in Jenkins container
      community.docker.docker_container_exec:
        container: jenkins
        command: >
          /bin/bash -c "chmod 666 /var/run/docker.sock"
        user: root   

    - name: Display initial Admin Password
      community.docker.docker_container_exec:
        container: jenkins
        command: cat /var/jenkins_home/secrets/initialAdminPassword
      register: admin_password_output

    - name: Print initial Admin Password
      debug:
        var: admin_password_output.stdout
